var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var cors = require("cors");
global.__basedir = path.resolve(path.dirname(''));


var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var login = require('./routes/login');
var disregform = require('./routes/disregform');
var districtview = require('./routes/districtview');
var locationreg = require('./routes/locationreg');
var locationview = require('./routes/locationview');
var ugregform = require('./routes/ugregform');
var upload = require('./routes/upload');
var ugview = require('./routes/ugview');
var pgregform = require('./routes/pgregform');
var categoryregfrom = require('./routes/categoryregfrom');
var catview = require('./routes/catview');
var ugviews = require('./routes/ugviews');
var pgview = require('./routes/pgview');
var deleteloc = require('./routes/deleteloc');
var deletepg = require('./routes/deletepg');
var uggview = require('./routes/uggview');
var deletecate = require('./routes/deletecate');
var disview = require('./routes/disview');
var deleteugcourse = require('./routes/deleteugcourse');
var possibleregform = require('./routes/possibleregform');
var possiblesview = require('./routes/possiblesview');
var possibleview = require('./routes/possibleview');
var deletepossible = require('./routes/deletepossible');
var deletedis = require('./routes/deletedis');
var getlocationdetails = require('./routes/getlocationdetails');
var locationedit = require('./routes/locationedit');
var getpgdetails = require('./routes/getpgdetails');
var updatepgdata = require('./routes/updatepgdata');
var editugv = require('./routes/editugv');
var updateugdata = require('./routes/updateugdata');
var catget = require('./routes/catget');
var updatecatdata = require('./routes/updatecatdata');
var disget = require('./routes/disget');
var updatedisdata = require('./routes/updatedisdata');
var collegereggroup = require('./routes/collegereggroup');
var collegepgr = require('./routes/collegepgr');
var collegepgv = require('./routes/collegepgv');
var collegepossibleregv = require('./routes/collegepossibleregv');
var collegepossiblereg = require('./routes/collegepossiblereg');
var collegepossiblecourseview = require('./routes/collegepossiblecourseview');
var deletecollegepg = require('./routes/deletecollegepg');
var deletecollegepossible = require('./routes/deletecollegepossible');
var collegeview = require('./routes/collegeview');
var collegeseatreg = require('./routes/collegeseatreg');
var collegeseatview = require('./routes/collegeseatview');
var deletecollegeseat = require('./routes/deletecollegeseat');
var collegeseatget = require('./routes/collegeseatget');
var seatedit = require('./routes/seatedit');
var admincollegeview = require('./routes/admincollegeview');
var admincollegeaccepted = require('./routes/admincollegeaccepted');
var admincollegerejected = require('./routes/admincollegerejected');
var adminstatusview = require('./routes/adminstatusview');
var userreggroup = require('./routes/userreggroup');
var usercollegeview = require('./routes/usercollegeview');
var usercollegepgcourseview = require('./routes/usercollegepgcourseview');
var collegeviewmore = require('./routes/collegeviewmore');
var collegepgcourseview = require('./routes/collegepgcourseview');
var userbook = require('./routes/userbook');
var collegepgcourseapplied = require('./routes/collegepgcourseapplied');
var collegepgcourseappliedcat = require('./routes/collegepgcourseappliedcat');
var collegeviewpg = require('./routes/collegeviewpg');
var collegetypeview = require('./routes/collegetypeview');
var collegeremark = require('./routes/collegeremark');
var collegeseatregcat = require('./routes/collegeseatregcat');
var collegeinterview = require('./routes/collegeinterview');
var userbookingpage = require('./routes/userbookingpage');
var userappliedbooking = require('./routes/userappliedbooking');
var collegeacceptedremark = require('./routes/collegeacceptedremark');
var collegerejectedremark = require('./routes/collegerejectedremark');
var collegeothersremark = require('./routes/collegeothersremark');
var advancespaymentaccepte = require('./routes/advancespaymentaccepte');
var paymentform = require('./routes/paymentform');
var userpaymentview = require('./routes/userpaymentview');
var possibleviewpiechart = require('./routes/possibleviewpiechart');
var adminpaymentview = require('./routes/adminpaymentview');
var adminuserreport = require('./routes/adminuserreport');
var adminpaymentdataewise = require('./routes/adminpaymentdataewise');
var adminseatcoursereport = require('./routes/adminseatcoursereport');
var adminuserregdataewise = require('./routes/adminuserregdataewise');
var userforgetpassword = require('./routes/userforgetpassword');
var userchangepassword = require('./routes/userchangepassword');
var collegepaymentview = require('./routes/collegepaymentview');
var userview = require('./routes/userview');
var userprofileedit = require('./routes/userprofileedit');
var ulocationviews = require('./routes/ulocationviews');
var updateuserprofile = require('./routes/updateuserprofile');
var collegeprofileedit = require('./routes/collegeprofileedit');
var updatecollegeprofile = require('./routes/updatecollegeprofile');
var collegefliterview = require('./routes/collegefliterview');
var collegepossibleviewforreg = require('./routes/collegepossibleviewforreg');
var collegepgcoursesem = require('./routes/collegepgcoursesem');
var possiblecollegecourse = require('./routes/possiblecollegecourse');   
var seatbookingpiechart = require('./routes/seatbookingpiechart');




var app = express();

app.use(cors());
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));


app.use('/', indexRouter);
app.use('/users', usersRouter);

app.use('/login', login);
app.use('/disregform', disregform);
app.use('/districtview', districtview);
app.use('/locationreg', locationreg);
app.use('/locationview', locationview);
app.use('/ugregform', ugregform);
app.use('/upload', upload);
app.use('/ugview', ugview);
app.use('/pgregform', pgregform);
app.use('/categoryregfrom', categoryregfrom);
app.use('/catview', catview);
app.use('/ugviews', ugviews);
app.use('/pgview', pgview);
app.use('/deleteloc', deleteloc);
app.use('/deletepg', deletepg);
app.use('/uggview', uggview);
app.use('/deletecate', deletecate);
app.use('/disview', disview);
app.use('/deleteugcourse', deleteugcourse);
app.use('/possibleregform', possibleregform);
app.use('/possiblesview', possiblesview);
app.use('/possibleview', possibleview);
app.use('/deletepossible', deletepossible);
app.use('/deletedis', deletedis);
app.use('/getlocationdetails', getlocationdetails);
app.use('/locationedit', locationedit);
app.use('/getpgdetails', getpgdetails);
app.use('/updatepgdata', updatepgdata);
app.use('/editugv', editugv);
app.use('/updateugdata', updateugdata);
app.use('/catget', catget);
app.use('/updatecatdata', updatecatdata);
app.use('/disget', disget);
app.use('/updatedisdata', updatedisdata);
app.use('/collegereggroup', collegereggroup);
app.use('/collegepgr', collegepgr);
app.use('/collegepgv', collegepgv);
app.use('/collegepossibleregv', collegepossibleregv);
app.use('/collegepossiblereg', collegepossiblereg);
app.use('/collegepossiblecourseview', collegepossiblecourseview);
app.use('/deletecollegepg', deletecollegepg);
app.use('/deletecollegepossible', deletecollegepossible);
app.use('/collegeview', collegeview);
app.use('/collegeseatreg', collegeseatreg);
app.use('/collegeseatview', collegeseatview);
app.use('/deletecollegeseat', deletecollegeseat);
app.use('/collegeseatget', collegeseatget);
app.use('/seatedit', seatedit);
app.use('/admincollegeview', admincollegeview);
app.use('/admincollegeaccepted', admincollegeaccepted);
app.use('/admincollegerejected', admincollegerejected);
app.use('/adminstatusview', adminstatusview);
app.use('/userreggroup', userreggroup);
app.use('/usercollegeview', usercollegeview);
app.use('/usercollegepgcourseview', usercollegepgcourseview);
app.use('/collegeviewmore', collegeviewmore);
app.use('/collegepgcourseview', collegepgcourseview);
app.use('/userbook', userbook);
app.use('/collegepgcourseapplied', collegepgcourseapplied);
app.use('/collegepgcourseappliedcat', collegepgcourseappliedcat);
app.use('/collegeviewpg', collegeviewpg);
app.use('/collegetypeview', collegetypeview);
app.use('/collegeremark', collegeremark); 
app.use('/collegeseatregcat', collegeseatregcat);
app.use('/collegeinterview', collegeinterview);
app.use('/userbookingpage', userbookingpage);
app.use('/userappliedbooking', userappliedbooking);
app.use('/collegeacceptedremark', collegeacceptedremark);
app.use('/collegerejectedremark', collegerejectedremark);
app.use('/collegeothersremark', collegeothersremark);
app.use('/advancespaymentaccepte', advancespaymentaccepte);
app.use('/paymentform', paymentform);
app.use('/userpaymentview', userpaymentview); 
app.use('/possibleviewpiechart', possibleviewpiechart);
app.use('/adminpaymentview', adminpaymentview);
app.use('/adminuserreport', adminuserreport);
app.use('/adminpaymentdataewise',adminpaymentdataewise);
app.use('/adminseatcoursereport',adminseatcoursereport); 
app.use('/adminuserregdataewise',adminuserregdataewise);
app.use('/userforgetpassword',userforgetpassword);
app.use('/userchangepassword',userchangepassword);
app.use('/collegepaymentview',collegepaymentview);
app.use('/userview',userview); 
app.use('/userprofileedit',userprofileedit);
app.use('/ulocationviews',ulocationviews);
app.use('/updateuserprofile',updateuserprofile);
app.use('/collegeprofileedit',collegeprofileedit);
app.use('/updatecollegeprofile',updatecollegeprofile);
app.use('/collegefliterview',collegefliterview);
app.use('/collegepossibleviewforreg',collegepossibleviewforreg); 
app.use('/collegepgcoursesem',collegepgcoursesem);
app.use('/possiblecollegecourse',possiblecollegecourse);
app.use('/seatbookingpiechart',seatbookingpiechart);


    
module.exports = app;
